#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentioMeter,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonarIn,        sensorSONAR_inch)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, bumpSwitch,     sensorDigitalIn)
#pragma config(Motor,  port1,           flashLight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Using the Bump Switch 
  Team Members: Kerry, Kevin, Steven
  Date: 2/26/2018
  Section: 1 and 2


  Task Description: Press the bumpswitch, turns on both motors, wait 3.5sec, then stop the motors.

*/

task main() {
	while(true) {
untilBump(bumpSwitch);
startMotor(rightMotor, 63);
startMotor(leftMotor, 63);
wait(3.5);
stopMotor(rightMotor);
stopMotor(leftMotor);
}
}
