#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentioMeter,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonarIn,        sensorSONAR_inch)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, bumpSwitch,     sensorDigitalIn)
#pragma config(Motor,  port1,           flashLight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:Using the Optical Shaft Encoder
  Team Members:Kerry Kevin Steven
  Date:2/26/18
  Section:4


  Task Description: Turn on both motors foward until encoder counts 480, then reverse, until 2.5 rotations of encoder have passed, once completed turn off motors.

*/

task main() {
	while(true) {
startMotor(leftMotor, 63);
startMotor(rightMotor, 63);
untilEncoderCounts(480,quad);
stopMotor(leftMotor);
stopMotor(rightMotor);
startMotor(leftMotor, -63);
startMotor(rightMotor, -63);
untilEncoderCounts(480,quad);
stopMotor(leftMotor);
stopMotor(rightMotor);
}
}
